# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Home
      title: This is the first menu item.
      path: homepage
      class: first
    - label: Second item
      path: entry/1
      submenu:
          - label: Sub 1
            path: entry/2
          - label: Sub 2
            class: menu-item-class
            path: entry/3
          - label: Sub 3
            path: entry/4
          - label: Sub 4
            class: sub-class
            path: page/3
    - label: All pages
      path: pages/
    - label: The Bolt site
      link: http://bolt.cm
      class: last

mymain:
    - label: Home
      path: /
      class: first
    - label: Páginas
      path: /pages
      submenu:
          - label: Sobre
            title: Everything about our company
            path: /page/about
          - label: Contacto
            title: Our contact page
            path: /page/contact
    - label: Produtos
      path: /products
    - label: Iniciar sessão
      path: /members?from=mainmenu

mymainsession:
    - label: Home
      path: /
      class: first
    - label: Páginas
      path: /pages
      submenu:
          - label: Sobre
            title: Everything about our company
            path: /page/about
          - label: Contacto
            title: Our contact page
            path: /page/contact
    - label: Produtos
      path: /products
    - label: Encerrar sessão
      path: /logout