# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

mymain:
    - label: Inicio
      enlabel: Home
      frlabel: Démarrer
      path: /
      class: first
    - label: Produtos
      enlabel: Products
      frlabel: Les produits
      path: /products
    - label: Sobre
      enlabel: About
      frlabel: Sur nous
      title: Tudo sobre nos
      entitle: Everything about us
      frtitle: Tout sur nous
      path: /page/about
    - label: Contacto
      enlabel: Contact
      frlabel: Contact
      title: Nossa pagina de contacto
      entitle: Out contact page
      frtitle: Notre page de contact
      path: /page/contact
      


#main:
#    - label: Home
#      title: This is the first menu item.
#      path: homepage
#      class: first
#    - label: Second item
#      path: entry/1
#      submenu:
#          - label: Sub 1
#            path: entry/2
#          - label: Sub 2
#            class: menu-item-class
#            path: entry/3
#          - label: Sub 3
#            path: entry/4
#          - label: Sub 4
#            class: sub-class
#            path: page/3
#    - label: All pages
#      path: pages/
#    - label: The Bolt site
#      link: http://bolt.cm
#      class: last